---
name: YAML Linting

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint YAML Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint .

      - name: Run Slack Notification
        if: always()
        uses: opslabhqx/action-slacknotify@v1
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
